# amd64 only - used by release workflow on ubuntu-latest
version: 2
project_name: cw-otlp-tag-enricher-otel-grpc

before:
  hooks:
    - go test ./...

builds:
  - id: bootstrap
    main: .
    binary: bootstrap
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: lambda
    formats:
      - zip
    name_template: "{{ .ProjectName }}-{{ .Arch }}"
    files:
      - none*
    ids:
      - bootstrap

checksum:
  name_template: "checksums-amd64.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  mode: keep-existing
  replace_existing_artifacts: true
  github:
    owner: W0n9
    name: cw-otlp-tag-enricher-otel-grpc
