# arm64 only - used by release workflow on ubuntu-24.04-arm
version: 2
project_name: cw-otlp-tag-enricher-otel-grpc

before:
  hooks:
    - go test ./...

builds:
  - id: bootstrap
    main: .
    binary: bootstrap
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: default
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    builds:
      - bootstrap

checksum:
  name_template: "checksums-arm64.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  mode: keep-existing
  replace_existing_artifacts: true
  github:
    owner: W0n9
    name: cw-otlp-tag-enricher-otel-grpc
